export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_CART = 'ADD_TO_CART'; 

export const LOAD_CART_FROM_LOCAL_STORAGE = 'LOAD_CART_FROM_LOCAL_STORAGE';

export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';

export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';

export const UPDATE_CART_ITEM_QUANTITY = 'UPDATE_CART_ITEM_QUANTITY';

export const SET_CART_COUNT = 'SET_CART_COUNT';